name=DLDisplay
version=1.1.0
author=Patrik Kőszegi
maintainer=koszegipatrik@gmail.com
sentence=A library for DL3416 and DL2416 displays.
paragraph=Provides control functions for the DL3416 and DL2416 alphanumeric displays including scrolling text, blinking, and full character testing.
category=Display
url=https://github.com/paco7828/vintage-displays
architectures=*